**Ashwini Khushal Barapatre**

**CS23118**

**ML Lab- 7**

**Aim : To apply Support Vector Machine for classification and analyze the impact
of different kernels jon model accuracy.**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [4]:
path="/content/drive/MyDrive/ML Dataset/pulsar_stars - pulsar_stars.csv"
df = pd.read_csv(path)
df.head(5)

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0

In [5]:
df.shape

(17898, 9)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17898 entries, 0 to 17897
Data columns (total 9 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Mean of the integrated profile                17898 non-null  float64
 1   Standard deviation of the integrated profile  17898 non-null  float64
 2   Excess kurtosis of the integrated profile     17898 non-null  float64
 3   Skewness of the integrated profile            17898 non-null  float64
 4   Mean of the DM-SNR curve                      17898 non-null  float64
 5   Standard deviation of the DM-SNR curve        17898 non-null  float64
 6   Excess kurtosis of the DM-SNR curve           17898 non-null  float64
 7   Skewness of the DM-SNR curve                  17898 non-null  float64
 8   target_class                                  17898 non-null  int64
dtypes: float64(8), int64(1)
memory usage: 1.2 MB

In [7]:
df.describe()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
count,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000
mean,111.079968,46.549532,0.477857,1.770279,12.614400,26.326515,8.303556,104.857709,0.091574
std,25.652935,6.843189,1.064040,6.167913,29.472897,19.470572,4.506092,106.514540,0.288432
min,5.812500,24.772042,-1.876011,-1.791886,0.213211,7.370432,-3.139270,-1.976976,0.000000
25%,100.929688,42.376018,0.027098,-0.188572,1.923077,14.437332,5.781506,34.960504,0.000000
50%,115.078125,46.947479,0.223240,0.198710,2.801839,18.461316,8.433515,83.064556,0.000000
75%,127.085938,51.023202,0.473325,0.927783,5.464256,28.428104,10.702959,139.309330,0.000000
max,192.617188,98.778911,8.069522,68.101622,223.392141,110.642211,34.539844,1191.000837,1.000000

In [8]:
df.columns

Index(['Mean of the integrated profile',
       'Standard deviation of the integrated profile',
       'Excess kurtosis of the integrated profile',
       'Skewness of the integrated profile', 'Mean of the DM-SNR curve',
       'Standard deviation of the DM-SNR curve',
       'Excess kurtosis of the DM-SNR curve', 'Skewness of the DM-SNR curve',
       'target_class'],
      dtype='object')

In [9]:
df.isnull().any().any()

np.False_

In [10]:
df.isnull().sum()

Mean of the integrated profile                  0
Standard deviation of the integrated profile    0
Excess kurtosis of the integrated profile       0
Skewness of the integrated profile              0
Mean of the DM-SNR curve                        0
Standard deviation of the DM-SNR curve          0
Excess kurtosis of the DM-SNR curve             0
Skewness of the DM-SNR curve                    0
target_class                                    0
dtype: int64

In [11]:
#print the rows with missing values
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Mean of the integrated profile, Standard deviation of the integrated profile, Excess kurtosis of the integrated profile, Skewness of the integrated profile, Mean of the DM-SNR curve, Standard deviation of the DM-SNR curve, Excess kurtosis of the DM-SNR curve, Skewness of the DM-SNR curve, target_class]
Index: []

In [12]:
df.columns.str.strip()

Index(['Mean of the integrated profile',
       'Standard deviation of the integrated profile',
       'Excess kurtosis of the integrated profile',
       'Skewness of the integrated profile', 'Mean of the DM-SNR curve',
       'Standard deviation of the DM-SNR curve',
       'Excess kurtosis of the DM-SNR curve', 'Skewness of the DM-SNR curve',
       'target_class'],
      dtype='object')

In [13]:
df = df.rename(columns={' Mean of the integrated profile': 'mean',
                        ' Standard deviation of the integrated profile': 'standard_deviation',
                        ' Excess kurtosis of the integrated profile': 'Excess_kurtoss',
                        ' Skewness of the integrated profile': 'skewness',
                        ' Mean of the DM-SNR curve': 'mean_DM-SNR_curve',
                        ' Standard deviation of the DM-SNR curve': 'std_DM-SNR_curve',
                        ' Excess kurtosis of the DM-SNR curve': 'Ex-kurtosis_DM-SNR',
                        ' Skewness of the DM-SNR curve': 'skewness_DM-SNR',
                        ' target_class': 'target_class'})

In [14]:
# assuming 'y is the target variable
X = df.drop(columns=['target_class'])
y = df['target_class']

In [15]:
#One-hot encode categorical variables
#X = pd.get_dummies(X)
X = pd.get_dummies(X, dtype=int)

In [16]:
X.columns

Index(['Mean of the integrated profile',
       'Standard deviation of the integrated profile',
       'Excess kurtosis of the integrated profile',
       'Skewness of the integrated profile', 'Mean of the DM-SNR curve',
       'Standard deviation of the DM-SNR curve',
       'Excess kurtosis of the DM-SNR curve', 'Skewness of the DM-SNR curve'],
      dtype='object')

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X, y, train_size=0.7,
                                               test_size=0.3, random_state=42)
X_train.shape, X_test.shape

((12528, 8), (5370, 8))

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
from sklearn.svm import SVC
#import metrics to comput accuracy
from sklearn.metrics import accuracy_score
svc = SVC()
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with default hyperparameters:{0:0.4f}'
.format(accuracy_score(y_test,y_pred)))

Model accuracy score with default hyperparameters:0.9790

In [20]:
svc = SVC(C=100.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with rbf kernal and c=100.0 hyperparameters:{0:0.4f}'
.format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernal and c=100.0 hyperparameters:0.9803

In [21]:
svc = SVC(C=1000.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with rbf kernal and c=1000.0 hyperparameters:{0:0.4f}'
.format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernal and c=1000.0 hyperparameters:0.9797

In [22]:
svc = SVC(kernel='linear', C=1.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with linear kernal and c=1.0 hyperparameters:{0:0.4f}'
.format(accuracy_score(y_test,y_pred)))

Model accuracy score with linear kernal and c=1.0 hyperparameters:0.9788

In [23]:
svc = SVC(kernel='linear', C=100.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with linear kernal and c=100.0 hyperparameters:{0:0.4f}'
.format(accuracy_score(y_test,y_pred)))

Model accuracy score with linear kernal and c=100.0 hyperparameters:0.9786

In [24]:
svc = SVC(kernel='linear', C=1000.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with linear kernal and c=1000.0 hyperparameters:{0:0.4f}'
.format(accuracy_score(y_test,y_pred)))

Model accuracy score with linear kernal and c=1000.0 hyperparameters:0.9786

In [25]:
svc = SVC(kernel='poly', C=1.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with poly kernal and c=1.0 hyperparameters:{0:0.4f}'
.format(accuracy_score(y_test,y_pred)))

Model accuracy score with poly kernal and c=1.0 hyperparameters:0.9769

In [26]:
svc = SVC(kernel='poly', C=100.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with poly kernal and c=100.0 hyperparameters:{0:0.4f}'
.format(accuracy_score(y_test,y_pred)))

Model accuracy score with poly kernal and c=100.0 hyperparameters:0.9793

In [27]:
svc = SVC(kernel='poly', C=1000.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with poly kernal and c=1000.0 hyperparameters:{0:0.4f}'
.format(accuracy_score(y_test,y_pred)))

Model accuracy score with poly kernal and c=1000.0 hyperparameters:0.9793

In [28]:
svc = SVC(kernel='sigmoid', C=1.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with sigmoid kernal and c=1.0 hyperparameters:{0:0.4f}'
.format(accuracy_score(y_test,y_pred)))

Model accuracy score with sigmoid kernal and c=1.0 hyperparameters:0.8773

In [29]:
svc = SVC(kernel='sigmoid', C=100.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with sigmoid kernal and c=100.0 hyperparameters:{0:0.4f}'
.format(accuracy_score(y_test,y_pred)))

Model accuracy score with sigmoid kernal and c=100.0 hyperparameters:0.8773

In [30]:
svc = SVC(kernel='sigmoid', C=1000.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with sigmoid kernal and c=1000.0 hyperparameters:{0:0.4f}'
.format(accuracy_score(y_test,y_pred)))

Model accuracy score with sigmoid kernal and c=1000.0 hyperparameters:0.8773

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
print("confusion Matrix : ")
cn = confusion_matrix(y_pred, y_test)
print(cn)

confusion Matrix :
[[4556  331]
 [ 328  155]]